import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Montserrat } from "next/font/google";
import { SanityLive } from "@/sanity/lib/live";

// Google Font Configuration
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});

// Local Font Configuration
const geistSans = localFont({
  src: "/fonts/GeistVF.woff", // Adjusted path for public folder
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff", // Adjusted path for public folder
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={montserrat.variable}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <main>
            <Header />
            {children}
            <Footer />
          </main>
          <SanityLive/>
        </body>
      </html>
    </ClerkProvider>
  );
}
